# Q1: Identity Twister: 
Create a function create_custom_identity(size, value, index) that takes three arguments:

size: Size of the square identity matrix (e.g., 4).

value: The value to insert at the specified index (e.g., 10).

index: A tuple representing the index (i, j) for the custom value.

The function should return a NumPy array representing the identity matrix with the specified value inserted at the given index.

In [12]:
import numpy as np # After installing the necessary librarie for the task, Import to begin 

In [13]:
# This function create_custom_identity(size, value, index) creates a custom identity with a given size, value and index.
def create_custom_identity(size, value, index):
    identity = np.eye(size)  # Create a NumPy identity matrix of the specified size

if 0 <= index[0] < size and 0 <= index [1] < size: # checks if index is within the valid range (0 to size-1) ELSE 
    identity[index[0], index[1]] = i # it sets the element at that index to 1.
return identity # returns created list.

i= int(input("Enter  value: "))# this prompts the user to enter a value and stores it as an integer in the variable i.
index= (1, 2)
       
twister = create_custom_identity(4, i, index)#this create_custom_identity(4, i, index) matrix calls the function with the three(3) arguments: size 4, filled with i (user input value)  and sets element at index 2 to 1. the Result is stored in Twister the variable{i.e Cstom identity matrix 
print (twister)# Prints Result(custom identity matrix)*

NameError: name 'size' is not defined

#CORRECTED CODE:

In [8]:
import numpy as np

# This function creates a custom identity matrix
def create_custom_identity(size, value, index):
    
        identity = np.eye(size)  # Creates a NumPy identity matrix of the specified size
        
        assert 0 <= index[0] < size and 0 <= index[1] < size, "Index is not allocatted."# This line checks if index is within the valid range (0 to size-1) ELSE it prints "Index is not allocatted "
    
        identity[index[0], index[1]] = value  # Set the element at the given index to the specified value
        return identity

# Specify the index where value will be set to 1 (1-based indexing)
index = (1, 2) 

# Prompt the user to enter a value
i = int(input("Enter a value: "))  # Converts Input value to integer

# Create the custom identity matrix
twister = create_custom_identity(4, i, index)

# Print the result (custom identity matrix)
print(twister)

Enter a value: 7
[[1. 0. 0. 0.]
 [0. 1. 7. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
