# Q4:Flattening the Terrain:
Write a function flatten_terrain(terrain_data) that takes a 3D NumPy array representing terrain data (e.g., height at each point) and returns a 2D NumPy array representing the flattened height map.

In [1]:
import numpy as np

def flatten_terrain(terrain_data):
    # Calculate the average height of the terrain
    average_height = np.mean(terrain_data)
    
    # Create a new terrain where all points have the average height
    flattened_terrain = np.full_like(terrain_data, average_height)
    
    return flattened_terrain

#Test
terrain_data = np.random.rand(3, 4, 5)  # Replace with your actual terrain data
flattened = flatten_terrain(terrain_data)
print("Flattened Terrain:")
print(flattened)

Flattened Terrain:
[[[0.49738117 0.49738117 0.49738117 0.49738117 0.49738117]
  [0.49738117 0.49738117 0.49738117 0.49738117 0.49738117]
  [0.49738117 0.49738117 0.49738117 0.49738117 0.49738117]
  [0.49738117 0.49738117 0.49738117 0.49738117 0.49738117]]

 [[0.49738117 0.49738117 0.49738117 0.49738117 0.49738117]
  [0.49738117 0.49738117 0.49738117 0.49738117 0.49738117]
  [0.49738117 0.49738117 0.49738117 0.49738117 0.49738117]
  [0.49738117 0.49738117 0.49738117 0.49738117 0.49738117]]

 [[0.49738117 0.49738117 0.49738117 0.49738117 0.49738117]
  [0.49738117 0.49738117 0.49738117 0.49738117 0.49738117]
  [0.49738117 0.49738117 0.49738117 0.49738117 0.49738117]
  [0.49738117 0.49738117 0.49738117 0.49738117 0.49738117]]]
